dotenv: .env

dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

wallets:
  from_key: ${PRIVATE_KEY}

networks:
    default: "ganache-local"
    ropsten:
      host: http://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
      eth_usd_price_feed: '0x83F00b902cbf06E316C95F51cbEeD9D2572a349a'
      verify: True
    mainnet-fork:
      host: http://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
      eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
      verify: False
    mainnet-fork-dev:
      host: http://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
      eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
      verify: False  
    development:
      verify: False
    ganache-local:
      verify: False
    ganache-local2:
      verify: False
    ganache-local4:
      verify: False
